factAnalyzers:
  default: [ApacheCXFFactAnalyzer, ApacheWinkFactAnalyzer, GuiceServletFactAnalyzer,
            JerseyFactAnalyzer, RESTEasyFactAnalyzer, RestletFactAnalyzer, JAXRSFactAnalyzer,
            SpringBeanFactAnalyzer,SpringMVCAnnotationFactAnalyzer,
            StrutsXmlFactAnalyzer, WSDDFactAnalyzer, WSDLFactAnalyzer, WebXmlFactAnalyzer, SOAPUnionFactAnalyzer,
            StrutsActionFactAnalyzer, HttpServletFactAnalyzer,
            UnionWebServiceFactAnalyzer, UnionServletFactAnalyzer]
outPutDirectory: ./output
tempDirectory: ./output
reportType: all

#  StrutsConfigXmlFactAnalyzer(里面的路由基本被jsp路径涵盖了)