factAnalyzers:
  default: [ApacheCXFFactAnalyzer, ApacheWinkFactAnalyzer, GuiceServletFactAnalyzer,
            HttpServletFactAnalyzer, JerseyFactAnalyzer, RESTEasyFactAnalyzer, RestletFactAnalyzer,
            SpringBeanFactAnalyzer,
            SpringMVCAnnotationFactAnalyzer, StrutsConfigXmlFactAnalyzer,
            StrutsXmlFactAnalyzer, WSDDFactAnalyzer, WSDLFactAnalyzer, WebXmlFactAnalyzer, SOAPUnionFactAnalyzer,
            UnionWebServiceFactAnalyzer, StrutsActionFactAnalyzer]
outPutDirectory: ./output
tempDirectory: ./output
reportType: all

#  UnionFactAnalyzer